[package]
name = "raccord-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
raccord-cache = { path = "../raccord-cache" }
raccord-ir = { path = "../raccord-ir" }
raccord-planner = { path = "../raccord-planner" }
raccord-rmap = { path = "../raccord-rmap" }
